name: CI

on:
  pull_request:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v13
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: cachix/cachix-action@v10
        with:
          name: tezos-checker
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build dependencies
        run: nix-shell --pure --run ':'
      - name: Build checker with e2eTestsHack
        run: nix-build -A michelson --arg doCheck false --arg e2eTestsHack true --out-link ./checker-e2eTestsHack
      - name: Run e2e tests
        run: nix-shell --pure --run "WRITE_GAS_PROFILES=$PWD/gas_profiles.json WRITE_GAS_COSTS=$PWD/gas-costs.json CHECKER_DIR=$PWD/checker-e2eTestsHack python e2e/main.py"
      - name: Generate profile plots
        run: nix-shell --pure --run "python e2e/plot-gas-profiles.py gas_profiles.json --output auction-gas-profiles.png"
      - uses: actions/upload-artifact@v2.2.4
        # we only upload artifacts on 'push' events, this is simply to have one set of artifacts
        # per commit.
        if: github.event_name == 'push'
        with:
          name: stats
          path: gas-costs.json
          if-no-files-found: error
      - uses: actions/upload-artifact@v2.2.4
        if: github.event_name == 'push'
        with:
          name: gas-profile-plots
          path: auction-gas-profiles.png
          if-no-files-found: error
